using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Camera : MonoBehaviour
{


    Vector3 target_dir = new Vector3(0, 0, 0);

    // Start is called before the first frame update
    void Start()
    {
       
    }

    // Update is called once per frame
    public void Update()
    {

        ////ѓJѓЃѓ‰Ћ‹“_€Ъ“® ЃiЉp“xЃj
        //if (Input.GetKeyDown(KeyCode.W))// W ‚р‰џ‚µ‚Ѕ‚Ж‚«
        //{
        //    target_dir = new Vector3(0, 0, 0);
        //}

        //if (Input.GetKeyDown(KeyCode.S))// S ‚р‰џ‚µ‚Ѕ‚Ж‚«
        //{
        //    target_dir = new Vector3(0, 0, -1);
        //}

        //if (Input.GetKeyDown(KeyCode.A))// A ‚р‰џ‚µ‚Ѕ‚Ж‚«
        //{
        //    target_dir = new Vector3(-1, 0, 0);   
        //}

        //if (Input.GetKeyDown(KeyCode.D))// D ‚р‰џ‚µ‚Ѕ‚Ж‚«
        //{
        //    target_dir = new Vector3(1, 0, 0);  
        //}
        
        //Quaternion rotation = Quaternion.LookRotation(target_dir);//Ѓ@X Y Z ‚М’l‚рЋќ‚Б‚Д‚­‚й
        //transform.rotation = Quaternion.Lerp(transform.rotation, rotation, Time.deltaTime * 5);

    }
}
